version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  install_singularity: &install_singularity
    run:
      name: Install Singularity
      command: |
        # # TODO only install if singularity is not yet present
        # # if type singularity > /dev/null; then exit 0; fi
        SINGULARITY_VER=2.5.1
        apt-get update; 
        apt-get install -y squashfs-tools libarchive-dev
        wget https://github.com/singularityware/singularity/releases/download/$SINGULARITY_VER/singularity-$SINGULARITY_VER.tar.gz
        tar xvf singularity-$SINGULARITY_VER.tar.gz
        cd singularity-$SINGULARITY_VER
        ./configure --prefix=/usr/local --sysconfdir=/etc
        make
        make install
        #conda install --yes -c conda-forge singularity
  install_kipoi_plugins: &install_kipoi_plugins
    run:
      name: Install kipoi plugins
      command: |
        pip install kipoi_interpret
        pip install kipoi_veff
        pip install kipoiseq
        pip install pyfaidx
        conda install --yes -c conda-forge fastparquet zarr numcodecs

  install_from_dev_requirements_py3x: &install_from_dev_requirements_py3x
    run:
      name: Install from dev-requirements-py3x.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda env create --name kipoi-env -f dev-requirements.yml
        source activate kipoi-env
        pip install -e .

  install_from_dev_requirements_py36: &install_from_dev_requirements_py36
    run:
      name: Install from dev-requirements-py36.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda create -n kipoi-env python=3.6
        source activate kipoi-env
        conda env update -f dev-requirements.yml
        pip install -e .



  install_pip_deps: &install_pip_deps
    run:
      name: Install pip dependencies
      command: pip install genomelake --no-deps
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: pip install '.[develop,vep]'
  install_requests: &install_requests
    run:
      name: Install requirements for requests correctly
      command: pip install requests
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: kipoi ls
  kipoi_ls: &activate_and_kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate kipoi-env
        kipoi ls
  # run_coveralls: &run_coveralls
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        mkdir test-reports
        pytest --cov=kipoi/ tests/ -n 4 --no-cov-on-fail --junitxml=test-reports/junit.xml
      no_output_timeout: 15m
  activate_and_run_tests: &activate_and_run_tests
    run:
      name: Run tests
      command: |
        source activate kipoi-env
        mkdir test-reports
        pytest --cov=kipoi/ tests/ -n 4 --no-cov-on-fail --junitxml=test-reports/junit.xml
      no_output_timeout: 15m
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: coveralls || true
  activate_and_run_coveralls: &activate_and_run_coveralls
    run:
      name: activate and run coveralls
      command: |
        source activate kipoi-env
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports


jobs:
  test-py36-yml:
    docker:
     - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py36
      - *activate_and_kipoi_ls
      - *activate_and_run_tests
      - *activate_and_run_coveralls
      - *store_test_results
      - *store_test_artifacts
  test-py3x-yml:
    docker:
     - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_from_dev_requirements_py3x
      - *activate_and_kipoi_ls
      - *activate_and_run_tests
      - *activate_and_run_coveralls
      - *store_test_results
      - *store_test_artifacts

  test-py36:
    docker:
      - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_singularity
      - *install_pip_deps
      - *install_kipoi
      - *install_kipoi_plugins
      - *kipoi_ls
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts

  test-py27:
    docker:
      - image: kipoi/miniconda:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_pip_deps
      - *install_singularity
      - *install_kipoi
      - *install_kipoi_plugins
      - *kipoi_ls
      - *run_tests
      - *store_test_results
      - *store_test_artifacts
          
  build-deploy-docs:
    docker:
      # - image: continuumio/miniconda3:4.3.14
      - image: continuumio/anaconda3:5.0.1
      # - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 60:0f:05:31:12:3d:bc:8b:df:9d:08:da:71:a5:43:b6
      - checkout
      - run:
          name: Install pip - Kipoi
          command: pip install -e .
      - run:
          name: Install build deps
          command: pip install nbconvert mkdocs pydoc-markdown
      - run:
          name: Build docs
          command: |
            cd docs/
            ./render_ipynb.bash
            pydocmd build
      - run:
          name: Deploy docs
          command: .circleci/deploy_docs.bash
workflows:
  version: 2

  # TODO - consider running the deploy only on
  # tag commits: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
  test-n-deploy:
    jobs:
      - test-py36
      - test-py27
      - test-py3x-yml

      - build-deploy-docs:
          requires:
            - test-py36
            - test-py27
          filters:
            branches:
              only:
                - master
                - test_deployment_script
