version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update -n base conda -c anaconda
  install_sys_deps: &install_sys_deps
    run:
      name: install build-essential
      command: apt-get update && apt-get install -y build-essential libz-dev libcurl3-dev libarchive-dev
  # install_singularity: &install_singularitymodel
  #   run:
  #     name: Install Singularity
  #     command: |
  #       conda install --yes -c conda-forge singularity

  install_singularity: &install_singularity
    run:
      name: Install Singularity
      command: |

        wget https://github.com/singularityware/singularity/releases/download/2.5.2/singularity-2.5.2.tar.gz
        tar xvf singularity-2.5.2.tar.gz
        cd singularity-2.5.2
        ./configure --prefix=/usr/local
        make
        make install

  install_kipoi_plugins: &install_kipoi_plugins
    run:
      name: Install kipoi plugins
      command: |
        pip install kipoi_interpret
        pip install kipoi_veff
        pip install kipoiseq
        pip install pyfaidx
        conda install --yes -c conda-forge fastparquet zarr numcodecs

  export_shortcuts: &export_shortcuts
    run:
      name: Export shortcuts
      command: |
        # for no good reason the wrong version of pytest is choosen by default...
        echo 'export PYTEST=$(conda info --base)/envs/kipoi-env/bin/pytest' >> $BASH_ENV
  install_from_dev_requirements_py36: &install_from_dev_requirements_py36
    run:
      name: Install from dev-requirements-py36.yml
      command: |
        echo 'export CI_JOB_PY_YAML="$CI_JOB_PY_YAML"' >> $BASH_ENV
        conda env create --name kipoi-env -f dev-requirements-py36.yml
        source activate kipoi-env
        pip install -e .
        git lfs install
        # ln -s /opt/conda/bin/python /usr/bin/python
  install_genomelake: &install_genomelake
    run:
      name: Install pip dependencies
      command: conda install -c bioconda genomelake
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: pip install '.[develop,vep]'
  install_requests: &install_requests
    run:
      name: Install requirements for requests correctly
      command: pip install requests
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: kipoi ls
  kipoi_ls: &activate_and_kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate kipoi-env
        kipoi ls
  # run_coveralls: &run_coveralls
  activate_and_run_tests: &activate_and_run_tests
    run:
      name: Run tests
      command: |
        source activate kipoi-env
        mkdir test-reports
        $PYTEST --cov=kipoi/ tests/ -p no:sugar --no-cov-on-fail --junitxml=test-reports/junit.xml
      no_output_timeout: 15m
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: coveralls || true
  activate_and_run_coveralls: &activate_and_run_coveralls
    run:
      name: activate and run coveralls
      command: |
        source activate kipoi-env
        coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports
  # deployment
  build_pypi_package: &build_pypi_package
    run:
      name: build python packages
      command: |
        source activate kipoi-env
        python setup.py sdist bdist_wheel
  conda_install_twine: &conda_install_twine
    run:
      name: Install twine
      command: conda install twine
  pypi_create_pypirc: &pypi_create_pypirc
    run:
      name: init .pypirc
      command: |
        echo -e "[distutils]" >> ~/.pypirc
        echo -e "index-servers = " >> ~/.pypirc
        echo -e "    pypi" >> ~/.pypirc
        echo -e "    testpypi" >> ~/.pypirc
        echo -e "" >> ~/.pypirc
        echo -e "[testpypi]" >> ~/.pypirc
        echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc
        echo -e "username: $TEST_PYPI_USERNAME" >> ~/.pypirc
        echo -e "password: $TEST_PYPI_PASSWORD" >> ~/.pypirc
        echo -e "[pypi]" >> ~/.pypirc
        echo -e "username: $PYPI_USERNAME" >> ~/.pypirc
        echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc

jobs:
  test-py36-yml:
    docker:
      - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      #- *install_sys_deps
      - *install_from_dev_requirements_py36
      #- *install_singularity
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *activate_and_run_tests
      - *activate_and_run_coveralls
      - *store_test_results
      - *store_test_artifacts
  build-deploy-docs:
    docker:
      # - image: continuumio/miniconda3:4.5.12
      - image: continuumio/anaconda3:5.0.1
      # - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 60:0f:05:31:12:3d:bc:8b:df:9d:08:da:71:a5:43:b6
      - checkout
      - run:
          name: Install pip - Kipoi
          command: pip install -e .
      - run:
          name: Install build deps
          command: pip install nbconvert==5.4.0 tornado==5.1.1 mkdocs pydoc-markdown
      - run:
          name: Build docs
          command: |
            cd docs/
            ./render_ipynb.bash
            pydocmd build
      - run:
          name: Deploy docs
          command: .circleci/deploy_docs.bash

  test-deploy-pypi:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      #- *install_sys_deps
      - *install_from_dev_requirements_py36
      #- *install_singularity
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *build_pypi_package
      - *conda_install_twine
      - *pypi_create_pypirc
      - run:
          name: upload to TestPyPI
          command: twine upload --repository testpypi dist/* --verbose
      - run:
          name: pip install from TestPyPI
          command: |
            pip install --user --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple kipoi --verbose
            python -c "import kipoi; print(kipoi.__version__)"

  productive-deploy-pypi:
    docker:
      - image: continuumio/miniconda3:4.7.10
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      #- *install_sys_deps
      - *install_from_dev_requirements_py36
      #- *install_singularity
      - *export_shortcuts
      - *activate_and_kipoi_ls
      - *build_pypi_package
      - *conda_install_twine
      - *pypi_create_pypirc
      - run:
          name: upload to PyPI
          command: twine upload --repository pypi dist/* --verbose
      - run:
          name: pip install from PyPI
          command: |
            pip install --user kipoi --verbose
            python -c "import kipoi; print(kipoi.__version__)"

workflows:
  version: 2

  # TODO - consider running the deploy only on
  # tag commits: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
  test-n-deploy:
    jobs:
      - test-py36-yml
      - build-deploy-docs:
          requires:
            - test-py36-yml
          filters:
            branches:
              only:
                - master
                - test_deployment_script
      - test-deploy-pypi:
          requires:
            - test-py36-yml
          filters:
            branches:
              only:
                - master
                - test_deployment_pypi
                - test_deployment_script
      - deploy-pypi:
          requires:
            - test-py36-yml
            - test-deploy-pypi
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - master
                - test_deployment_script
