version: 2
jobs:

  test-py36:
    docker:
      - image: kipoi/miniconda3:4.3.14

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install genomelake
          command: |
            pip install git+ssh://git@github.com/avsecz/genomelake.git --no-deps

      - run:
          name: install the kipoi package
          command: |
            pip install '.[develop]'

      - run:
          name: list models
          command: |
            kipoi ls

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir test-reports
            py.test --cov=kipoi/ tests/ -n 4 --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-py27:
    docker:
      - image: kipoi/miniconda:4.3.14

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install genomelake
          command: |
            pip install git+ssh://git@github.com/avsecz/genomelake.git --no-deps

      - run:
          name: install the kipoi package
          command: |
            pip install '.[develop]'

      - run:
          name: list models
          command: |
            kipoi ls

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir test-reports
            py.test --cov=kipoi/ tests/ -n 4 --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
workflows:
  version: 2
  test_py27_py36:
    jobs:
      - test-py36
      - test-py27
